name: datter
description: Extension for flutter usecase, including widgets or non-widgets.
version: 0.0.1
repository: https://github.com/nomagicisreal/datter

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  damath: ^0.0.26
  flutter:
    sdk: flutter

  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0
