name: datter
description: project for common flutter usecase.
version: 0.0.5
repository: https://github.com/nomagicisreal/datter

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  damath: ^0.0.30
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true