name: datter
description: project for common flutter usecase.
version: 0.0.16
repository: https://github.com/nomagicisreal/datter

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  damath: ^0.0.34

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true