name: datter
description: project for common flutter usecase.
version: 0.0.19
repository: https://github.com/nomagicisreal/datter

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4
  damath: ^0.0.39
  overlay_model: ^0.0.2
  mationani: ^0.0.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true